[package]
name = "encoder"
version = "0.1.0"
edition = "2021"
description = "An audio encoder cli using ffmpeg."
license = "MIT"
repository = "git+https://github.com/jadujoel/snake.git"

[dependencies]
ffmpeg-cli = "0.1.0"
futures = "0.3.25"
path-clean = "0.1.0"
tokio = "1.22.0"
clap = { version = "4.0.27", features = ["derive"] }

[[bin]]
name = "encoder"
path = "src/main.rs"
