[package]
name = "snake"
version = "0.1.0"
edition = "2021"
description = "A snake game written in Rust"
license = "MIT"
repository = "https://github.com/jadujoel/snake.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
getrandom = { version = "0.2.8", features = ["js"] }
wasm-bindgen = "0.2.83"
wee_alloc = "0.4.5"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
