[package]
name = "app"
version = "0.1.0"
edition = "2021"
description = "A yew app for the snake game."
license = "MIT"
repository = "git+https://github.com/jadujoel/snake.git"

[dependencies]
yew = "0.19.3"
yew-hooks = "0.1.56" # use interval
wee_alloc = "0.4.5"
gloo = "0.8.0"
wasm-bindgen = "0.2.83"
rand = "0.8.5"
getrandom = { version = "0.2.8", features = ["js"] }
wasm-bindgen-futures = "0.4.33"
js-sys = "0.3.60"
reqwest = "0.11.13"
seek_bufread = "1.2.2"

[lib]
crate-type = ["rlib", "cdylib"]

[dev-dependencies]
encoder = { path = "../encoder" }

[dependencies.web-sys]
version = "0.3.60"
features = [
  'CanvasRenderingContext2d',
  'HtmlCanvasElement',
  'KeyboardEvent',
  'AudioContext',
  'AudioDestinationNode',
  'AudioNode',
  'AudioParam',
  'AudioBuffer',
  'AudioBufferSourceNode',
  'GainNode',
  'OscillatorNode',
  'OscillatorType',
  'Headers',
  'Request',
  'RequestInit',
  'RequestMode',
  'Response',
  'Window',
]
