[package]
name = "app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.19.3"
wee_alloc = "0.4.5"
yewtil = "0.4.0"
gloo = "0.8.0"
wasm-bindgen = "0.2.83"
rand = "0.8.5"
getrandom = { version = "0.2.8", features = ["js"] }
yew-hooks = "0.1.56"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies.web-sys]
version = "0.3.60"
features = [
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'HtmlCanvasElement',
  'Window',
]
