name: Deploy
on:
  push:
    branches: ["main"]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: jetli/wasm-pack-action@v0.3.0
      - uses: oven-sh/setup-bun@v1
      - uses: FedericoCarboni/setup-ffmpeg@v2
      - run: bun install turbo && bun run build
      - uses: actions/configure-pages@v2.1.1
      - uses: actions/upload-pages-artifact@v1.0.4
        with:
          path: 'packages/app/dist'
      - id: deployment
        uses: actions/deploy-pages@v1.2.2
